### ISSUE TITLE
certain package errors can crash

### ISSUE THREAD

**Issue by dholth** [conda-incubator/conda-index#24]
```
2022-06-07T12:24:01 Error extracting libpython-static-3.10.0-hc377ac9_2.tar.bz2
Traceback (most recent call last):
  File "/home/dholth/prog/conda-index/conda_index/index/sqlitecache.py", line 218, in _extract_to_cache
    index_json = self.extract_to_cache_unconditional(
  File "/home/dholth/prog/conda-index/conda_index/index/sqlitecache.py", line 254, in extract_to_cache_unconditional
    for tar, member in package_stream:
  File "/home/dholth/prog/conda-index/conda_index/index/package_streaming.py", line 23, in tar_generator
    for member in tar:
  File "/home/dholth/miniconda3/envs/conda-index/lib/python3.10/tarfile.py", line 2465, in __iter__
    tarinfo = self.next()
  File "/home/dholth/miniconda3/envs/conda-index/lib/python3.10/tarfile.py", line 2332, in next
    self.fileobj.seek(self.offset - 1)
  File "/home/dholth/miniconda3/envs/conda-index/lib/python3.10/tarfile.py", line 513, in seek
    self.read(self.bufsize)
  File "/home/dholth/miniconda3/envs/conda-index/lib/python3.10/tarfile.py", line 522, in read
    buf = self._read(size)
  File "/home/dholth/miniconda3/envs/conda-index/lib/python3.10/tarfile.py", line 530, in _read
    return self.__read(size)
  File "/home/dholth/miniconda3/envs/conda-index/lib/python3.10/tarfile.py", line 560, in __read
    buf = self.fileobj.read(self.bufsize)
  File "/home/dholth/miniconda3/envs/conda-index/lib/python3.10/bz2.py", line 164, in read
    return self._buffer.read(size)
  File "/home/dholth/miniconda3/envs/conda-index/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/dholth/miniconda3/envs/conda-index/lib/python3.10/_compression.py", line 99, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

We've known this package was bad for a while now. It must have crashed while it was being compressed. Looks like we need to catch `EOFError` in `sqlitecache`

**Comment by dholth** [comment]
We do catch that error, there may be a different bug parsing non-hotfixed repodata from packages. Also might be a good idea to show a shorter traceback here.
